backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    path: '{{slug}}/index'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'page'
    label: 'Pages'
    folder: 'content/page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Menu', name: 'menu', widget: "select", multiple: true, options: ["main", "footer" ] }
      - { label: 'Ordre dans le menu', name: 'weight', widget: "number" }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: "pagescustom"
    label: "Pages personnalisées"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Menu', name: 'menu', widget: "select", multiple: true, options: [ "main", "footer" ] }
          - { label: 'Ordre dans le menu', name: 'weight', widget: "number" }
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
            {label: "Heading", name: "heading", widget: string},
            {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
            {label: "Heading", name: "heading", widget: string},
            {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
            {label: "Heading", name: "heading", widget: string},
            {label: "Text", name: "text", widget: "text"}]}